import { CategoryTreeNode } from "@/types/Category.types";

// Mock category tree data
export const MOCK_CATEGORY_TREE: CategoryTreeNode[] = [
  {
    _id: "1",
    name: "Electronics",
    slug: "electronics",
    description: "Electronic devices and accessories",
    parentId: null,
    level: 0,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        _id: "1-1",
        name: "Smartphones",
        slug: "electronics-smartphones",
        description: "Mobile phones and accessories",
        parentId: "1",
        level: 1,
        isActive: true,
        sortOrder: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [
          {
            _id: "1-1-1",
            name: "iPhone",
            slug: "electronics-smartphones-iphone",
            parentId: "1-1",
            level: 2,
            isActive: true,
            sortOrder: 1,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
          {
            _id: "1-1-2",
            name: "Android",
            slug: "electronics-smartphones-android",
            parentId: "1-1",
            level: 2,
            isActive: true,
            sortOrder: 2,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
        ],
      },
      {
        _id: "1-2",
        name: "Laptops",
        slug: "electronics-laptops",
        description: "Laptops and notebooks",
        parentId: "1",
        level: 1,
        isActive: true,
        sortOrder: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [
          {
            _id: "1-2-1",
            name: "Gaming Laptops",
            slug: "electronics-laptops-gaming",
            parentId: "1-2",
            level: 2,
            isActive: true,
            sortOrder: 1,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
          {
            _id: "1-2-2",
            name: "Business Laptops",
            slug: "electronics-laptops-business",
            parentId: "1-2",
            level: 2,
            isActive: true,
            sortOrder: 2,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
        ],
      },
      {
        _id: "1-3",
        name: "Tablets",
        slug: "electronics-tablets",
        parentId: "1",
        level: 1,
        isActive: true,
        sortOrder: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [],
      },
    ],
  },
  {
    _id: "2",
    name: "Clothing",
    slug: "clothing",
    description: "Fashion and apparel",
    parentId: null,
    level: 0,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        _id: "2-1",
        name: "Men's Clothing",
        slug: "clothing-mens",
        parentId: "2",
        level: 1,
        isActive: true,
        sortOrder: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [
          {
            _id: "2-1-1",
            name: "T-Shirts",
            slug: "clothing-mens-tshirts",
            parentId: "2-1",
            level: 2,
            isActive: true,
            sortOrder: 1,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
          {
            _id: "2-1-2",
            name: "Jeans",
            slug: "clothing-mens-jeans",
            parentId: "2-1",
            level: 2,
            isActive: true,
            sortOrder: 2,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
        ],
      },
      {
        _id: "2-2",
        name: "Women's Clothing",
        slug: "clothing-womens",
        parentId: "2",
        level: 1,
        isActive: true,
        sortOrder: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [
          {
            _id: "2-2-1",
            name: "Dresses",
            slug: "clothing-womens-dresses",
            parentId: "2-2",
            level: 2,
            isActive: true,
            sortOrder: 1,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
          {
            _id: "2-2-2",
            name: "Tops",
            slug: "clothing-womens-tops",
            parentId: "2-2",
            level: 2,
            isActive: true,
            sortOrder: 2,
            createdAt: new Date(),
            updatedAt: new Date(),
            children: [],
          },
        ],
      },
      {
        _id: "2-3",
        name: "Kids' Clothing",
        slug: "clothing-kids",
        parentId: "2",
        level: 1,
        isActive: true,
        sortOrder: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [],
      },
    ],
  },
  {
    _id: "3",
    name: "Home & Garden",
    slug: "home-garden",
    description: "Home improvement and garden supplies",
    parentId: null,
    level: 0,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [
      {
        _id: "3-1",
        name: "Furniture",
        slug: "home-garden-furniture",
        parentId: "3",
        level: 1,
        isActive: true,
        sortOrder: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [],
      },
      {
        _id: "3-2",
        name: "Kitchen",
        slug: "home-garden-kitchen",
        parentId: "3",
        level: 1,
        isActive: true,
        sortOrder: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        children: [],
      },
    ],
  },
];
