import type { Metadata } from "next";
import { Concert_One, Inter } from "next/font/google";

import Header from "@/components/layout/Header";
import { ToastContainer, ToastContextProvider } from "@gratia/ui";
import "./globals.scss";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const concertOne = Concert_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-concert-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${concertOne.variable}`}>
        <ToastContextProvider>
          <Header />
          {children}
          <ToastContainer />
        </ToastContextProvider>
      </body>
    </html>
  );
}
